apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: catalogo-db-pvc
  namespace: conveniencia
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogo-db
  namespace: conveniencia
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalogo-db
  template:
    metadata:
      labels:
        app: catalogo-db
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: catalogo_db
            - name: POSTGRES_USER
              value: catalogo
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: conveniencia-secret
                  key: CATALOGO_DB_PASSWORD
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "catalogo", "-d", "catalogo_db"]
            initialDelaySeconds: 5
            periodSeconds: 10
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: catalogo-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: catalogo-db
  namespace: conveniencia
spec:
  selector:
    app: catalogo-db
  ports:
    - port: 5432
      targetPort: 5432
